apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: yaml-modify

spec:
  entrypoint: yaml-modify
  
  arguments:
    parameters:
    - name: config-repo
      value: https://github.com/tkrausjr/cd-kubernetes.git
    - name: revision
      value: master
    - name: harbor-server
      value: "harbor.tpmlab.vmware.com"
      ## This is a workflow Global Parameter access it with
      ## {{workflow.parameters.harbor-server}}
    - name: image-repo
      value: "library/argo-repo"
    - name: image-tag
      value: "argo-tag"

  templates:
  - name: yaml-modify
    steps:
    
    # If Golang test results=ok, Run Makefile to build the Golang Source into Binary
    - - name: update-image
        template: update-image

    
  - name: update-image
    script:
      image: mytkrausjr/python-slim:git6
      command: ["/bin/sh"]
      source: |
        cd /home 
        git clone {{workflow.parameters.config-repo}} 
        cd cd-kubernetes 
        git config user.email "tkrausjr@gmail.com" 
        git remote set-url origin git@github.com:tkrausjr/cd-kubernetes.git 
        git remote -v 
        ssh -o "StrictHostKeyChecking=no" -T git@github.com 
        python3 /home/yaml-subs.py -f ./go-reminders/overlays/prod/kustomization.yaml -s argoserver -r argorepo -t argowf-tag2999
        git remote -v 
        git add . 
        git commit -am "Updating Image Tag" 
        git push origin master
      
      resources:
        requests:
          memory: 1024Mi
          cpu: 200m

  
